version: '3.8'

services:
  db:
    image: postgres:16 
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: kgnAdmin 
      POSTGRES_PASSWORD: 8515
      POSTGRES_DB: kgn_db 
    ports:
      - "5432:5432" 
    volumes:
      - pg_data:/var/lib/postgresql/data 

volumes:
  pg_data: